// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/BotanicalLetterpressBusinessCard-s8raha/App.tsx": () => import("../components/mockups/templates/BotanicalLetterpressBusinessCard-s8raha/App.tsx"),
  "./components/mockups/templates/WarmLanguageLearningDashboard-fNaw8R/App.tsx": () => import("../components/mockups/templates/WarmLanguageLearningDashboard-fNaw8R/App.tsx")
};
